export default () => {
  return [
    {
      id: 1,
      name: 'amande',
      type: 'Toppings',
      size: 'S',
      price: 4,
      dispo: true,
      info: 'some info',
      img: '',
      allerg: '',
      compatible: 'tout',
    },
    {
      id: 2,
      name: 'amande',
      type: 'Toppings',
      size: 'M',
      price: 5,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: '',
      compatible: 'tout',
    },
    {
      id: 3,
      name: 'amande',
      type: 'Toppings',
      size: 'XL',
      price: 6,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: '',
      compatible: 'tout',
    },
    {
      id: 4,
      name: 'cerise',
      type: 'Toppings',
      size: 'S',
      price: 2,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
    },
    {
      id: 4,
      name: 'cerise',
      type: 'Toppings',
      size: 'M',
      price: 3,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
    },
    {
      id: 6,
      name: 'cerise',
      type: 'Toppings',
      size: 'XL',
      price: 4,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
    },
    {
      id: 7,
      name: 'chocolat',
      type: 'Toppings',
      size: 'S',
      price: 2,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
    },
    {
      id: 8,
      name: 'chocolat',
      type: 'Toppings',
      size: 'M',
      price: 3,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
    },
    {
      id: 9,
      name: 'chocolat',
      type: 'Toppings',
      size: 'XL',
      price: 5,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
    },
  ];
};
