export default () => { 
  return [
    {
      id: 1,
      name: 'base banane',
      type: 'Base',
      size: 'S',
      price: 10,
      dispo: true,
      info: 'some info',
      img: '',
      allerg: 'gluten',
      compatible: ['remplissage citron', 'Glaçage citron'],
    },
    {
      id: 2,
      name: 'base banane',
      type: 'Base',
      size: 'M',
      price: 12,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: ['remplissage citron', 'Glaçage citron'],
    },
    {
      id: 3,
      name: 'base banane',
      type: 'Base',
      size: 'XL',
      price: 16,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: ['remplissage citron', 'Glaçage citron'],
    },
    {
      id: 4,
      name: 'base cookie',
      type: 'Base',
      size: 'S',
      price: 10,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: ['remplissage framboise', 'Glaçage framboise'],
    },
    {
      id: 4,
      name: 'base cookie',
      type: 'Base',
      size: 'M',
      price: 12,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: ['remplissage framboise', 'Glaçage framboise'],
    },
    {
      id: 6,
      name: 'base cookie',
      type: 'Base',
      size: 'XL',
      price: 16,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: ['remplissage framboise', 'Glaçage framboise'],
    },
    {
      id: 7,
      name: 'base vanille',
      type: 'Base',
      size: 'S',
      price: 10,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: ['remplissage fraise', 'Glaçage fraise'],
    },
    {
      id: 8,
      name: 'base vanille',
      type: 'Base',
      size: 'M',
      price: 13,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: ['remplissage fraise', 'Glaçage fraise'],
    },
    {
      id: 9,
      name: 'base vanille',
      type: 'Base',
      size: 'XL',
      price: 17,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: ['remplissage fraise', 'Glaçage fraise'],
    },
  ];
};
