export default () => {
  return [
    {
      id: 1,
      name: 'glacage framboise',
      type: 'glacage',
      size: 'S',
      price: 4,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: '',
      compatible: 'garniture citron',
    },
    {
      id: 2,
      name: 'glacage framboise',
      type: 'glacage',
      size: 'M',
      price: 5,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: '',
      compatible: 'garniture citron',
    },
    {
      id: 3,
      name: 'glacage framboise',
      type: 'glacage',
      size: 'XL',
      price: 6,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: '',
      compatible: 'garniture citron',
    },
    {
      id: 4,
      name: 'glacage citron',
      type: 'glacage',
      size: 'S',
      price: 2,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture framboise',
    },
    {
      id: 4,
      name: 'glacage citron',
      type: 'glacage',
      size: 'M',
      price: 3,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture framboise',
    },
    {
      id: 6,
      name: 'glacage citron',
      type: 'glacage',
      size: 'XL',
      price: 4,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture framboise',
    },
    {
      id: 7,
      name: 'glacage orange',
      type: 'glacage',
      size: 'S',
      price: 2,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture fraise',
    },
    {
      id: 8,
      name: 'glacage orange',
      type: 'glacage',
      size: 'M',
      price: 3,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture fraise',
    },
    {
      id: 9,
      name: 'glacage orange',
      type: 'glacage',
      size: 'XL',
      price: 5,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture fraise',
    },
  ];
};
