export default () =>{ 
  return [
    {
      id: 1,
      name: 'base banane',
      type: 'base',
      size: 'S',
      price: 10,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture citron',
    },
    {
      id: 2,
      name: 'base banane',
      type: 'base',
      size: 'M',
      price: 12,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture citron',
    },
    {
      id: 3,
      name: 'base banane',
      type: 'base',
      size: 'XL',
      price: 16,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture citron',
    },
    {
      id: 4,
      name: 'base cookie',
      type: 'base',
      size: 'S',
      price: 10,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture framboise',
    },
    {
      id: 4,
      name: 'base cookie',
      type: 'base',
      size: 'M',
      price: 12,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture framboise',
    },
    {
      id: 6,
      name: 'base cookie',
      type: 'base',
      size: 'XL',
      price: 16,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture framboise',
    },
    {
      id: 7,
      name: 'base vanille',
      type: 'base',
      size: 'S',
      price: 10,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture fraise',
    },
    {
      id: 8,
      name: 'base vanille',
      type: 'base',
      size: 'M',
      price: 13,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture fraise',
    },
    {
      id: 9,
      name: 'base vanille',
      type: 'base',
      size: 'XL',
      price: 17,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'garniture fraise',
    },
  ];
};
