// import getDescription from '../Actions/getDescription';

export default () => {
  return [
    {
      id: 1,
      name: 'remplissage amande',
      type: 'Filling',
      size: 'S',
      price: 4,
      dispo: true,
      info: 'some info',
      img: '',
      allerg: '',
      compatible: 'tout',
      // fullDescription: getDescription(this),
    },
    {
      id: 2,
      name: 'remplissage amande',
      type: 'Filling',
      size: 'M',
      price: 5,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: '',
      compatible: 'tout',
      // fullDescription: getDescription(this),
    },
    {
      id: 3,
      name: 'remplissage amande',
      type: 'Filling',
      size: 'XL',
      price: 6,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: '',
      compatible: 'tout',
      // fullDescription: getDescription(this),
    },
    {
      id: 4,
      name: 'remplissage cerise',
      type: 'Filling',
      size: 'S',
      price: 2,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
    },
    {
      id: 4,
      name: 'remplissage cerise',
      type: 'Filling',
      size: 'M',
      price: 3,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
    },
    {
      id: 6,
      name: 'remplissage cerise',
      type: 'Filling',
      size: 'XL',
      price: 4,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
    },
    {
      id: 7,
      name: 'remplissage chocolat',
      type: 'Filling',
      size: 'S',
      price: 2,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
    },
    {
      id: 8,
      name: 'remplissage chocolat',
      type: 'Filling',
      size: 'M',
      price: 3,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
    },
    {
      id: 9,
      name: 'remplissage chocolat',
      type: 'Filling',
      size: 'XL',
      price: 5,
      dispo: true,
      info: 'some info',
      img: 'https://via.placeholder.com/150',
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
    },
  ];
};
