import base_banane from '../Assets/Images/base_banane.png';
import base_vanille from '../Assets/Images/base_vanille.png';
import base_chocolat from '../Assets/Images/base_chocolat.png'

export default () => { 
  return [
    {
      id: 1,
      name: 'base banane',
      type: 'Base',
      size: 'S',
      price: 10,
      dispo: true,
      info: 'some info',
      img: base_banane,
      allerg: 'gluten',
      compatible: ['fourrage citron', 'Glaçage citron'],
      isCompatibe: true,
    },
    {
      id: 2,
      name: 'base banane',
      type: 'Base',
      size: 'M',
      price: 12,
      dispo: true,
      info: 'some info',
      img: base_banane,
      allerg: 'gluten',
      compatible: ['fourrage citron', 'Glaçage citron'],
      isCompatibe: true,
    },
    {
      id: 3,
      name: 'base banane',
      type: 'Base',
      size: 'XL',
      price: 16,
      dispo: true,
      info: 'some info',
      img: base_banane,
      allerg: 'gluten',
      compatible: ['fourrage citron', 'Glaçage citron'],
      isCompatibe: true,
    },
    {
      id: 4,
      name: 'base chocolat',
      type: 'Base',
      size: 'S',
      price: 10,
      dispo: true,
      info: 'some info',
      img: base_chocolat,
      allerg: 'gluten',
      compatible: ['fourrage framboise', 'Glaçage framboise'],
      isCompatibe: true,
    },
    {
      id: 4,
      name: 'base chocolat',
      type: 'Base',
      size: 'M',
      price: 12,
      dispo: true,
      info: 'some info',
      img: base_chocolat,
      allerg: 'gluten',
      compatible: ['fourrage framboise', 'Glaçage framboise'],
      isCompatibe: true,
    },
    {
      id: 6,
      name: 'base chocolat',
      type: 'Base',
      size: 'XL',
      price: 16,
      dispo: true,
      info: 'some info',
      img: base_chocolat,
      allerg: 'gluten',
      compatible: ['fourrage framboise', 'Glaçage framboise'],
      isCompatibe: true,
    },
    {
      id: 7,
      name: 'base vanille',
      type: 'Base',
      size: 'S',
      price: 10,
      dispo: true,
      info: 'some info',
      img: base_vanille,
      allerg: 'gluten',
      compatible: ['fourrage fraise', 'Glaçage fraise'],
      isCompatibe: true,
    },
    {
      id: 8,
      name: 'base vanille',
      type: 'Base',
      size: 'M',
      price: 13,
      dispo: true,
      info: 'some info',
      img: base_vanille,
      allerg: 'gluten',
      compatible: ['fourrage fraise', 'Glaçage fraise'],
      isCompatibe: true,
    },
    {
      id: 9,
      name: 'base vanille',
      type: 'Base',
      size: 'XL',
      price: 17,
      dispo: true,
      info: 'some info',
      img: base_vanille,
      allerg: 'gluten',
      compatible: ['fourrage fraise', 'Glaçage fraise'],
      isCompatibe: true,
    },
  ];
};
