// import getDescription from '../Actions/getDescription';
import filling_vanille from '../Assets/Images/filling_vanille.png';
import filling_fraise from '../Assets/Images/filling_fraise.png';
import filling_citron from '../Assets/Images/filling_citron.png'

export default () => {
  return [
    {
      id: 1,
      name: 'fourrage vanille',
      type: 'Filling',
      size: 'S',
      price: 4,
      dispo: true,
      info: 'some info',
      img: filling_vanille,
      allerg: '',
      compatible: 'tout',
      // fullDescription: getDescription(this),
      isCompatibe: false,
    },
    {
      id: 2,
      name: 'fourrage vanille',
      type: 'Filling',
      size: 'M',
      price: 5,
      dispo: true,
      info: 'some info',
      img: filling_vanille,
      allerg: '',
      compatible: 'tout',
      // fullDescription: getDescription(this),
      isCompatibe: false,
    },
    {
      id: 3,
      name: 'fourrage vanille',
      type: 'Filling',
      size: 'XL',
      price: 6,
      dispo: true,
      info: 'some info',
      img: filling_vanille,
      allerg: '',
      compatible: 'tout',
      // fullDescription: getDescription(this),
      isCompatibe: false,
    },
    {
      id: 4,
      name: 'fourrage fraise',
      type: 'Filling',
      size: 'S',
      price: 2,
      dispo: true,
      info: 'some info',
      img: filling_fraise,
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
      isCompatibe: false,
    },
    {
      id: 4,
      name: 'fourrage fraise',
      type: 'Filling',
      size: 'M',
      price: 3,
      dispo: true,
      info: 'some info',
      img: filling_fraise,
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
      isCompatibe: false,
    },
    {
      id: 6,
      name: 'fourrage fraise',
      type: 'Filling',
      size: 'XL',
      price: 4,
      dispo: true,
      info: 'some info',
      img: filling_fraise,
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
      isCompatibe: false,
    },
    {
      id: 7,
      name: 'fourrage citron',
      type: 'Filling',
      size: 'S',
      price: 2,
      dispo: true,
      info: 'some info',
      img: filling_citron,
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
      isCompatibe: false,
    },
    {
      id: 8,
      name: 'fourrage citron',
      type: 'Filling',
      size: 'M',
      price: 3,
      dispo: true,
      info: 'some info',
      img: filling_citron,
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
      isCompatibe: false,
    },
    {
      id: 9,
      name: 'fourrage citron',
      type: 'Filling',
      size: 'XL',
      price: 5,
      dispo: true,
      info: 'some info',
      img: filling_citron,
      allerg: 'gluten',
      compatible: 'tout',
      // fullDescription: getDescription(this),
      isCompatibe: false,
    },
  ];
};
