export default () => [
  {
    id: 1,
    color: 'red',
    colorCode: 'rgba(255,0,0,1)',
    type: 'Coquille',
    size: 'S',
    price: 4,
    dispo: true,
    info: 'some info',
    img: '',
    allerg: '',
    compatible: ['macaron'],
  },
  {
    id: 2,
    color: 'green',
    colorCode: 'rgba(0,255,0,1)',
    type: 'Coquille',
    size: 'S',
    price: 4,
    dispo: true,
    info: 'some info',
    img: '',
    allerg: '',
    compatible: ['macaron'],
  },
  {
    id: 3,
    color: 'blue',
    colorCode: 'rgba(0,0,255,1)',
    type: 'Coquille',
    size: 'S',
    price: 4,
    dispo: true,
    info: 'some info',
    img: '',
    allerg: '',
    compatible: ['macaron'],
  },
];
